### ISSUE TITLE
Uart flags

### ISSUE THREAD

**Issue by VaporMontey** [technexion-android/platform_packages_apps_UartTestAarch64#1]
Hello,

I'm trying to implement the serial communication using this test app but I have to configure the flags on the port (parity, stop bits, ecc), where do I find the documentation?

Best regards

**Comment by wigcheng** [comment]
This is a very simple demo without detail setting (even no CTS/RTS), so you might be implement by yourself.

But don't worry, it's the same as Linux, you just need implement API in JNI first as follows path:

https://github.com/technexion-android/platform_packages_apps_UartTestAarch64/blob/tn-p9.0.0_2.0.0_8m-ga/jni/SerialPort.c

See that, it also use #include <termios.h>, it's the same with Linux, so you can read termios document first, and try to do some simple change, should be works.
